function createfigure(X1, Y1, XData1, YData1)
%CREATEFIGURE(X1, Y1, XDATA1, YDATA1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  XDATA1:  line xdata
%  YDATA1:  line ydata

%  Auto-generated by MATLAB on 30-Aug-2017 12:50:15

% Create figure
figure('PaperSize',[25 10],'NumberTitle','off',...
    'Name','Prosthesis Simulation',...
    'OuterPosition',[9.286875 12.8852083333333 15.24 13.573125]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Color',[0 0 1]);

% Create line
line(XData1,YData1,'LineWidth',2,'LineStyle','--','Color',[0 1 0]);

% Create xlabel
xlabel('Time [s]');

% Create title
title('Prosthesis Simulation');

% Create ylabel
ylabel('Angle [°dd]');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 40]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 135]);
box(axes1,'on');
